name = "Fapcraft"
author = "Dispnser"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c927a4ce71f4d3c74de63c3734258b999ce5e1e2cd57a960e9accef65b2fee4"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
